---
title: "Untitled"
author: "Nick Gauthier"
date: "3/13/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(sf)
library(stars)
library(tidyverse)
library(exactextractr)
```

```{r}
devtools::load_all()
hyde_names <- c('cropland', 'grazing', 'ir_rice', 'popc', 'tot_irri', 'uopp')
```


```{r}
hyde_merge <- function(varname, indir, outdir = NULL) {
  time_fac <-  factor(sort(time_steps), levels = time_steps)

 list.files(indir, pattern = '*.asc', recursive = TRUE, full.names = TRUE) %>%
    str_subset(varname) %>%
    .[order(test_fac)] %>% # correc file order, could also use to subset times if given as an argument
    read_stars(proxy = TRUE, along = 'time') %>%
    st_set_crs(4326) %>%
    setNames(varname) %>%
    st_set_dimensions('time', values = time_steps) %>%
    write_stars(paste0(outdir, varname, '.tif'))
}

hyde_names %>%
  walk(hyde_merge, indir = '/Volumes/Data/baseline/zip', outdir = '~/Desktop/')
```

]

can I write to zip too?
```{r}
#Creation of a new zip file:

fmain = VSIFOpenL("/vsizip/my.zip", "wb");
subfile = VSIFOpenL("/vsizip/my.zip/subfile", "wb");
VSIFWriteL("Hello World", 1, strlen("Hello world"), subfile);
VSIFCloseL(subfile);
VSIFCloseL(fmain);
#Addition of a new file to an existing zip:
newfile = VSIFOpenL("/vsizip/my.zip/newfile", "wb");
VSIFWriteL("Hello World", 1, strlen("Hello world"), newfile);
VSIFCloseL(newfile);
```


```{r}
hyde <- file.path('/vsizip/', 
                  'Users/nick/Desktop/HYDE.zip', 
                  paste0(hyde_names, '.tif')) %>%
  read_stars(proxy = TRUE) %>% # could use RasterIO = list(bands = xxx) to select bands
  setNames(., str_remove(names(.), '.tif')) %>%
  st_set_dimensions('band', names = 'time')
```

```{r}
bbox <- st_bbox(c(xmin = 32, xmax = 42, ymin = 30, ymax = 40), crs = 4326)


ggplot() +
  geom_stars(data = st_crop(hyde, bbox) %>% .[,,,1:12] ) +
  facet_wrap(~time) +
  coord_quickmap() +
  scale_fill_viridis_c()
```

```{r}
dgg <- read_sf('analysis/data/derived_data/dgg_land.shp', crs = 4326) %>%
  dplyr::select(-L1_ID)
```

```{r}
hyde2dgg_stars <- function(var, dgg, path) {
  # could add check if path is zip or not
  file.path('/vsizip/', path, paste0(var, '.tif')) %>%
    raster::stack() %>%
    {suppressWarnings(raster::brick(.))} %>% 
    exact_extract(dgg, 'sum', append_cols = dgg$geometry, progress = TRUE) %>%
    rename_with(str_remove, pattern = 'sum.X') %>% 
    st_as_sf() %>% 
    st_as_stars() %>%
    merge(name = 'time') %>%
    setNames(var)
}
library(furrr)
plan(multisession, workers = 2)
hyde_dgg <- hyde_names %>%
  .[1:2] %>%
  # change this and the following paths to point to the HYDE data on your machine
  future_map(hyde2dgg_stars, dgg = dgg, path = 'Users/nick/Desktop/HYDE.zip') %>%
  do.call(c, .)
```


```{r}

hyde

hyde_dgg %>% 
  setNames(hyde_names) %>%
  bind_rows(.id = 'var')

hyde_to_stars <- function(dat, var, dgg) {
  left_join(dat, dgg, by = 'ANL12_ID') %>%
  st_as_sf %>%
  st_as_stars %>%
  select(-ANL12_ID) %>%
  merge() %>%
  setNames(var) %>%
  st_set_dimensions(names = c('geometry', 'time'))
}

t3 <- map2(hyde$data, hyde$var, hyde_to_stars, dgg = dgg) %>%
   do.call(c, .)
```

```{r}
system.time(

)

system.time(test <- brick('~/Desktop/HYDE/cropland.tif')%>%exact_extract(dgg_land, 'sum', progress = TRUE)
)

system.time(test <- stack('~/Desktop/HYDE/cropland.tif') %>% crop(bbox) %>%exact_extract(dgg, 'sum', progress = TRUE)
)


system.time(test <- stack('~/Desktop/HYDE/cropland.tif') %>% crop(bbox) %>%exact_extract(dgg2, 'sum', progress = TRUE)
)

remotes::install_github('isciences/exactextractr')

 raster::brick('~/Desktop/HYDE/cropland.tif')
 
 suppressWarnings(test <- raster::stack('~/Desktop/HYDE/cropland.tif') %>% raster::brick() %>% exact_extract(dgg, 'sum', progress = TRUE))
 
suppressWarnings(test <- raster::brick('~/Desktop/HYDE/cropland.tif')%>%exact_extract(dgg, 'sum', progress = TRUE))
```

```{r}
system.time(
hyde_dgg3 <- aggregate(hyde, dgg, sum, na.rm = TRUE, exact = TRUE))
```

```{r}
system.time(
hyde_dgg <- file.path('/Users/nick/Desktop/HYDE', 
                  paste0(hyde_names, '.tif')) %>%
  raster::stack() %>%
  exact_extract(dgg, 'sum', progress = TRUE)
)

system.time(
hyde_dgg2 <- file.path('Users/nick/Desktop/HYDE', 
                  paste0(hyde_names, '.tif')) %>%
  map(~exact_extract(brick(.x), dgg, 'sum', progress = TRUE))
)

library(raster)


```


```{r}
file.path('/vsizip/', 
                  'Users/nick/Desktop/HYDE.zip', 
                  paste0(hyde_names, '.tif')) %>%
  raster::stack() %>% plot
```




```{r}
hyde_dgg <- exact_extract(raster::brick('test.tif'), dgg, 'sum', progress = TRUE)
```




```{r}
hyde <- readRDS('analysis/data/derived_data/hyde_dgg') %>% 
  as_tibble() %>%
  filter(ANL12_ID %in% dgg$ANL12_ID) %>%
  group_nest(var)
```

```{r}
map(hyde_varname)
```



```{r}
hyde_to_stars <- function(dat, var, dgg) {
  left_join(dat, dgg, by = 'ANL12_ID') %>%
  st_as_sf %>%
  st_as_stars %>%
  select(-ANL12_ID) %>%
  merge() %>%
  setNames(var) %>%
  st_set_dimensions(names = c('geometry', 'time'))
}

st_as_stars((((hyde$data[[1]]))), sf_geometry = dgg$geometry)

hyde$data[[1]] %>% pivot_longer(cols = -ANL12_ID, names_to = 'time') %>% pivot_wider(time, names_from = ANL12_ID) %>% st_as_stars(sf_geomettry = dgg)

saveRDS(t3, 't3.rds') 

```
  
```{r}
t3 <- map2(hyde$data, hyde$var, hyde_to_stars, dgg = dgg) %>%
   do.call(c, .)
```

```{r}
ggplot() +
  geom_stars(data = t3['popc',,c(42)] ) +
  facet_wrap(~time) +
  scale_fill_viridis_c(trans = 'log')
```


```{r}



hyde <- list.files('/Volumes/Data/baseline/zip', recursive = TRUE, full.names = TRUE) %>%
  str_subset('cropland') %>%
  read_stars(proxy = TRUE, along = 'time') %>%
  st_set_crs(4326) %>%
  setNames('cropland') %>%
  st_set_dimensions('time', values = test_fac) 

test %>%
  st_crop(bbox) %>% 
  plot

st_get_dimension_values(test, 'time')
```

```{r}

test2 <- test %>%
 # st_set_dimensions(which = 'time', values = test_fac, names = 'time') %>%
  st_crop(bbox) %>% 
  st_as_stars 


test2[,,,order(test_fac)] %>% .[,,,10:20] %>% plot

ggplot() +
  geom_stars(data = test2[,,,order(test_fac)] %>% .[,,,10:20] ) +
  facet_wrap(~time) +
  coord_quickmap() +
  scale_fill_viridis_c()
```



```{r}
hyde2dgg <- function(hyde_varname, dgg, hyde_path){
  suppressWarnings(
    hyde <- list.files(hyde_path, recursive = TRUE, full.names = TRUE) %>% # does this catch the zip files too? better to unzip here?
      str_subset(hyde_varname) %>%
      map(raster) %>%
      brick() %>%
      `crs<-`(value = '+proj=longlat +datum=WGS84 +no_defs +ellps=WGS84 +towgs84=0,0,0') %>%
      exact_extract(dgg, 'sum', progress = TRUE)
  )
  time_steps <- names(hyde) %>%
    str_sub(start = str_length(hyde_varname) + 5) %>%
    str_remove('_')

  setNames(hyde, time_steps) %>%
    mutate(ANL12_ID = dgg$ANL12_ID, .before = 1)
}


  time_steps <- names(hyde) %>%
    str_sub(start = str_length(hyde_varname) + 5) %>%
    str_remove('_')

  setNames(hyde, time_steps) %>%
    mutate(ANL12_ID = dgg$ANL12_ID, .before = 1)
```

```{r}
hyde2dgg <- function(hyde_varname, dgg, hyde_path){
  suppressWarnings(
    hyde <- list.files(hyde_path, recursive = TRUE, full.names = TRUE) %>% # does this catch the zip files too? better to unzip here?
      str_subset(hyde_varname) %>%
      map(raster) %>%
      brick() %>%
      `crs<-`(value = '+proj=longlat +datum=WGS84 +no_defs +ellps=WGS84 +towgs84=0,0,0') %>%
      exact_extract(dgg, 'sum', progress = TRUE)
  )
  time_steps <- names(hyde) %>%
    str_sub(start = str_length(hyde_varname) + 5) %>%
    str_remove('_')

  setNames(hyde, time_steps) %>%
    mutate(ANL12_ID = dgg$ANL12_ID, .before = 1)
}
```


```{r}
library(ncdfgeom)
write_stars(t3, 'hyde.shp')
tif = system.file("tif/L7_ETMs.tif", package = "stars")
x <- tif %>% read_stars
plot(x)

write_stars(x, 'test.nc')
read_stars('test.nc') %>% plot
x %>% st_xy2sfc(as_points = FALSE) %>% st_as_sf %>% write_sf('test.nc')

write_stars(adrop(t3['cropland']), 'cropland.nc')

```


```{r}
t3 %>% mutate(test =)
t2 <- dgg %>% 
  mutate(area = st_area(geometry)) %>%
  st_as_stars %>%
  select(area)

st_apply(t3[,,1:2], 1:2, function(x) x * t2)

```

