---
title: "Anthromes"
author: "Nick Gauthier"
date: "6/30/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(stars)
library(tidyverse)
library(sf)
library(dggridR)
library(patchwork)


anthrome_key <- tibble(
  anthrome = c(11, 12, 21, 22, 23, 24, 31, 32, 33, 34, 41, 42, 43, 51, 
            52, 53, 54, 61, 62, 63, 70),
  class = factor(c('Urban', 'Mixed settlements', 'Rice villages', 'Irrigated villages', 
            'Rainfed villages', 'Pastoral villages', 'Residential irrigated croplands',
            'Residential rainfed croplands', 'Populated croplands', 'Remote croplands', 
            'Residential rangelands', 'Populated rangelands', 'Remote rangelands', 
            'Residential woodlands', 'Populated woodlands', 'Remote woodlands', 
            'Inhabited treeless & barren lands', 'Wild woodlands', 
            'Wild treeless and barren lands', 'Ice, uninhabited', 'NODATA'), 
            levels = c('Urban', 'Mixed settlements', 'Rice villages', 'Irrigated villages', 
            'Rainfed villages', 'Pastoral villages', 'Residential irrigated croplands',
            'Residential rainfed croplands', 'Populated croplands', 'Remote croplands', 
            'Residential rangelands', 'Populated rangelands', 'Remote rangelands', 
            'Residential woodlands', 'Populated woodlands', 'Remote woodlands', 
            'Inhabited treeless & barren lands', 'Wild woodlands', 
            'Wild treeless and barren lands', 'Ice, uninhabited', 'NODATA')),
  level = factor(c('Dense settlements', 'Dense settlements', 'Villages', 'Villages', 
            'Villages', 'Villages', 'Croplands', 'Croplands', 'Croplands', 'Croplands', 
            'Rangelands', 'Rangelands', 'Rangelands', 'Seminatural', 'Seminatural', 
            'Seminatural', 'Seminatural', 'Wildlands', 'Wildlands', 'Wildlands', 'NODATA'), 
            levels = c('Dense settlements', 'Villages', 'Croplands',
            'Rangelands', 'Seminatural', 'Wildlands', 'NODATA')),
  type = factor(c('Used', 'Used', 'Used', 'Used', 'Used', 'Used', 'Used', 'Used', 'Used', 
           'Used', 'Used', 'Used', 'Used', 'Seminatural', 'Seminatural','Seminatural', 
           'Seminatural', 'Wild', 'Wild', 'Wild', 'NODATA'), levels = c('Used', 'Seminatural', 'Wild', 'NODATA'))
)

anthrome_class_color <- c('#A80000', '#FF0000', '#0070FF', '#00A9E6', '#A900E6', 
                  '#FF73DF', '#00FFC5', '#E6E600', '#FFFF73', '#FFFFBE', 
                  '#E69800', '#FFD37F', '#FFEBAF', '#38A800', '#A5F57A', 
                  '#D3FFB2', '#B2B2B2', '#DAF2EA', '#E1E1E1', '#FAFFFF', NA) %>%
  setNames(anthrome_key$class)

anthrome_level_color <- c('Dense settlements' = '#CD6666', 'Villages' = '#AA66CD', 'Croplands' = '#FFFF00', 
                 'Rangelands' = '#FFAA00', 'Seminatural' = '#D3FFBE', 'Wildlands' = '#38A800', NODATA = NA)

anthrome_type_color <- c('Used' = '#EDCDCB', 'Seminatural' = '#FFFFFF', 'Wild' = '#CADAA9', NODATA = NA)

anthrome_class_color2 <- c('#A80000', '#FF0000', '#0070FF', '#00A9E6', '#A900E6', 
                  '#FF73DF', '#00FFC5', '#E6E600', '#FFFF73', '#FFFFBE', 
                  '#E69800', '#FFD37F', '#FFEBAF', '#38A800', '#A5F57A', 
                  '#D3FFB2', '#B2B2B2', '#DAF2EA', '#E1E1E1', '#FAFFFF', NA) %>%
  setNames(c(11, 12, 21, 22, 23, 24, 31, 32, 33, 34, 41, 42, 43, 51, 
            52, 53, 54, 61, 62, 63, 70))

time_steps <- c("10000BC", "9000BC", "8000BC", "7000BC", "6000BC", "5000BC", "4000BC", "3000BC", "2000BC", "1000BC", "0AD", "100AD", "200AD", "300AD", "400AD", "500AD", "600AD", "700AD", "800AD", "900AD", "1000AD", "1100AD", "1200AD", "1300AD", "1400AD", "1500AD", "1600AD",  "1700AD",  "1710AD",  "1720AD",  "1730AD",  "1740AD",  "1750AD",  "1760AD", "1770AD", "1780AD", "1790AD", "1800AD", "1810AD", "1820AD", "1830AD", "1840AD", "1850AD", "1860AD", "1870AD", "1880AD", "1890AD", "1900AD", "1910AD", "1920AD", "1930AD", "1940AD", "1950AD", "1960AD", "1970AD", "1980AD", "1990AD", "2000AD", "2001AD", "2002AD", "2003AD", "2004AD", "2005AD", "2006AD", "2007AD", "2008AD", "2009AD", "2010AD", "2011AD", "2012AD", "2013AD", "2014AD", "2015AD", "2016AD", "2017AD") 

time_steps_ordered <- factor(time_steps, levels = time_steps, ordered = TRUE)
 
recent_time_steps <-  c("2012AD",  "2013AD",  "2014AD",  "2015AD",  "2016AD",  "2017AD")
 
 time_steps_millennia <- c("10000BC", "9000BC", "8000BC", "7000BC", "6000BC", "5000BC", "4000BC", "3000BC", "2000BC", "1000BC", "0AD", "1000AD", "2000AD")
 
time_steps_centuries <- c("0AD", "100AD", "200AD", "300AD", "400AD", "500AD", "600AD", "700AD", "800AD", "900AD", "1000AD", "1100AD", "1200AD", "1300AD", "1400AD", "1500AD", "1600AD",  "1700AD",  "1800AD",  "1900AD", "2000AD")
 
 time_steps_decades <- c("1700AD", "1710AD",  "1720AD",  "1730AD",  "1740AD",  "1750AD",  "1760AD", "1770AD", "1780AD", "1790AD", "1800AD", "1810AD", "1820AD", "1830AD", "1840AD", "1850AD", "1860AD", "1870AD", "1880AD", "1890AD", "1900AD", "1910AD", "1920AD", "1930AD", "1940AD", "1950AD", "1960AD", "1970AD", "1980AD", "1990AD", "2000AD", "2010AD", "2017AD")
 
 years <- c(seq(-10000, -1000, 1000), 1,
           seq(100, 1700, 100),
           seq(1710, 2000, 10),
           seq(2001, 2017, 1))
 
time_key <- tibble(time_step = time_steps_ordered, year = years)

period_key <- tibble(time_step = time_steps_ordered) %>%
  mutate(millennia = time_step %in% time_steps_millennia,
         centuries = time_step %in% time_steps_centuries,
         decades = time_step %in% time_steps_decades)

biome_key <- tibble(biome_value = 1:15) %>%
  mutate(biome = case_when(biome_value == 1 ~ 'Tropical evergreen woodland',
                                         biome_value == 2 ~ 'Tropical deciduous woodland',
                                         biome_value %in% c(3, 4, 5) ~ 'Temperate woodland',
                                         biome_value %in% c(6, 7) ~ 'Boreal woodland',
                                         biome_value == 8 ~ 'Mixed woodland',
                                         biome_value %in% c(9, 10) ~ 'Grassland, savanna, steppe',
                                         biome_value %in% c(11, 12) ~ 'Shrubland',
                                         biome_value == 13 ~ 'Tundra',
                                         biome_value == 14 ~ 'Desert and barren',
                                         biome_value == 15 ~ 'Ice, snow'),
         # define levels so plots have correct order
         biome = factor(biome, levels = c('Tropical evergreen woodland', 'Tropical deciduous woodland', 'Temperate woodland', 'Boreal woodland', 'Mixed woodland', 'Grassland, savanna, steppe', 'Shrubland', 'Tundra',	'Desert and barren', 'Ice, snow')))
```

# Setup

Import preprocessed data.

```{r}
an12_dgg_inputs <- read_sf('an12_dgg_inputs.shp')  %>% st_set_crs(4326)
an12_dgg <- read_csv('an12_dgg.csv')

total_land_area <- sum(an12_dgg_inputs$land_area)

contemp_vars <- read_sf('contemp_vars.shp') %>%
   mutate(pa = pa_km2 > 0, ind = ind_cnt > 0, kba = kba_km2 > 0, pa50 = pa_km2 > 50, ind50 = ind_cnt > 50, kba50 = kba_km2 > 50, v_rich = round(v_rich), v_thr = round(v_thr), hfp_max = round(hfp_max)) # won't make a difference, but this should technically be > 50% area, rather than just 50, but here the scales even out
```



# Figure 1 - Summary
```{r}
anthromes_summary <- an12_dgg %>% 
  left_join(st_drop_geometry(an12_dgg_inputs), by = 'id') %>%
  select(-pot_veg, -pot_vill) %>%
  pivot_longer(-c(id, land_area), names_to = 'time_step', values_to = 'anthrome') %>%
  mutate(anthrome= as.factor(anthrome)) %>%
  count(time_step, anthrome, wt = land_area, name = 'land_area', .drop = FALSE) %>%
  mutate(percent_land_area = land_area / total_land_area,
         anthrome = as.numeric(as.character(anthrome))) %>%
  left_join(anthrome_key, by = 'anthrome') %>%
  left_join(time_key, by = 'time_step') %>%
  mutate(period = case_when(year %in% c(seq(-10000, -1000, 1000), 1) ~ 'Millennia',
                            year %in% seq(100, 1700, 100) ~ 'Centuries',
                            year %in%  c(seq(1710, 2010, 10), 2017) ~ 'Decades'),
         period = factor(period, c('Millennia', 'Centuries', 'Decades'))) %>%
  arrange(year, anthrome) %>%
  select(time_step, anthrome, class, percent_land_area, period, year)
```

```{r}
write_csv(anthromes_summary, 'an12_dgg_summary.csv')
```


Get hyde population data.
```{r}
hyde_pop <- readRDS('hyde_dgg') %>%
  select(contains('popc')) %>%
  summarise_all(sum, na.rm = TRUE) %>% 
  gather(key, population) %>%
  separate(key, into = c('var', 'time_step'), sep  = '_') %>%
  select(-var) %>%
  left_join(time_key) %>%
  select(year, population) %>%
  mutate(period = case_when(year %in% c(seq(-10000, -1000, 1000), 1) ~ 'Millennia',
                            year %in% seq(100, 1700, 100) ~ 'Centuries',
                            year %in% c(seq(1710, 2010, 10), 2017) ~ 'Decades'),
         period = factor(period, c('Millennia', 'Centuries', 'Decades'))) %>%
  mutate(pop_percent = population / max(population))
```

Summary by total land area.

```{r, fig.width=9, fig.height=3.5}
a <- anthromes_summary %>%
 ggplot(aes(as.factor(year), percent_land_area)) +
#  geom_area(aes(fill = class, color = class), position = 'stack') +
#  geom_col(aes(fill = class), color = 'lightgrey', size = .2)+
  geom_col(aes(fill = class, color = class), size = 1)+
  geom_hline(yintercept = c(.25, .50, .75), linetype = 2, alpha = .3) +
  geom_line(data = hyde_pop, aes(x = as.factor(year), y = pop_percent), color = 'maroon', linetype = 1, group = 1, size = 1.2) + 
  #geom_label(aes(label = label), data = tibble(year = 20010,  percent_land_area = 1, label = 'Population', period = factor('Decades', c('Millennia', 'Centuries', 'Decades')))) +
 facet_grid(~period, scales = 'free_x', space = 'free') +
  scale_color_manual(values = anthrome_class_color, name = 'Anthrome') +
  scale_fill_manual(values = anthrome_class_color, name = 'Anthrome') +
      theme_classic() +
  scale_y_continuous(labels = scales::percent, expand = c(0,0.02)) +
  scale_x_discrete(breaks = c(-10000, -5000, 1, 500, 1000, 1700, 1800, 1900, 2000),
                   labels = c('10000 ʙᴄᴇ', '5000 ʙᴄᴇ', '1 ᴄᴇ', '500 ᴄᴇ', '1000 ᴄᴇ', '1700 ᴄᴇ', '1800 ᴄᴇ', '1900 ᴄᴇ', '2000 ᴄᴇ')) +
  labs(x = 'Year', y = 'Percent land surface') +
  theme(legend.position = 'bottom', plot.margin = margin(.2, .2,.2, r = .5, unit = 'cm'))
a

addSmallLegend <- function(myPlot, pointSize = 3, textSize = 8, spaceLegend = .8) {
    myPlot +
        guides(shape = guide_legend(override.aes = list(size = pointSize)),
               color = guide_legend(override.aes = list(size = pointSize))) +
        theme(legend.text  = element_text(size = textSize),
              legend.key.size = unit(spaceLegend, "lines"))
}

a <- addSmallLegend(a)
ggsave('anthrome_areas_population.png', width = 9, height = 3.5)
```


```{r}
library(exactextractr)
regions_dgg <- raster::raster('../simple_regions.tif') %>%
  exact_extract(an12_dgg_inputs, 'mode')

region_key <- tibble(region = 1:8, region_name = c('Eurasia', 'Latin America', 'Near East', 'Africa', 'Asia', 'Europe', 'North America', 'Oceania'))


#left_join(an12_dgg_inputs,   mutate(an12_dgg, region = regions_dgg, land_area = an12_dgg_inputs$land_area)) %>%      left_join(region_key) %>%
 # ggplot() +
#  geom_sf(aes(fill = region_name), color = NA)
```

```{r}
region_summary <- an12_dgg %>% 
  mutate(region = regions_dgg, land_area = an12_dgg_inputs$land_area) %>%
  pivot_longer(-c(id, land_area, region), names_to = 'time_step', values_to = 'anthrome') %>%
    mutate(anthrome= as.factor(anthrome), region = as.factor(region)) %>%
  count(time_step, anthrome, region, wt = land_area, name = 'land_area', .drop = FALSE) %>%
  mutate(percent_land_area = land_area / total_land_area,
                  anthrome = as.numeric(as.character(anthrome)),
         region = as.numeric(as.character(region))) %>%
  left_join(anthrome_key, by = 'anthrome') %>%
  left_join(time_key, by = 'time_step') %>%
  mutate(period = case_when(year %in% c(seq(-10000, -1000, 1000), 1) ~ 'Millennia',
                            year %in% seq(100, 1700, 100) ~ 'Centuries',
                            year %in% c(seq(1710, 2010, 10), 2017) ~ 'Decades'),
         period = factor(period, c('Millennia', 'Centuries', 'Decades'))) %>%
  arrange(year, region, anthrome) %>%
    left_join(region_key) %>%
  select(time_step, region_name, anthrome, class, percent_land_area, period, year)

write_csv(region_summary, 'an12_dgg_summary_region.csv')
```


```{r, fig.height = 9, fig.width = 8}

b <- region_summary %>% 
 ggplot(aes(as.factor(year), percent_land_area)) +
  geom_col(aes(fill = class, color = class), size = 1)+ 
   facet_grid(region_name~period, scales = 'free', space = 'free_x') +
  scale_color_manual(values = anthrome_class_color, name = 'Anthrome') +
  scale_fill_manual(values = anthrome_class_color, name = 'Anthrome') +
      theme_classic() +
  scale_y_continuous(labels = scales::percent_format(accuracy = 1), expand = c(0,0)) +
  scale_x_discrete(breaks = c(-10000, -5000, 1, 500, 1000, 1700, 1800, 1900, 2000),
                   labels = c('10000 ʙᴄᴇ', '5000 ʙᴄᴇ', '1 ᴄᴇ', '500 ᴄᴇ', '1000 ᴄᴇ', '1700 ᴄᴇ', '1800 ᴄᴇ', '1900 ᴄᴇ', '2000 ᴄᴇ')) +
  labs(x = 'Year', y = expression('Percent land surface')) +
  theme(legend.position = 'none')
  #theme(axis.text.x = element_text(angle = 45, vjust = 0.9, hjust=1), legend.position = 'bottom')
  
b
theme(legend.position = 'bottom', plot.margin = margin(.2, .2,.2, r = .5, unit = 'cm'))
ggsave('anthromes_summary_region.png', height = 9, width = 8)
```

```{r, fig.height=8, fig.width = 5}
a / b + plot_layout(heights = c(1, 4))
```
```{r, fig.width = 10, fig.height=6}
map_dat <-  an12_dgg_inputs %>%
  left_join(an12_dgg) %>%
  transmute(anthrome = `2017AD`) %>%
  left_join(anthrome_key)

  ggplot(map_dat) +
  geom_sf(aes(fill = class), color = NA) +
  scale_fill_manual(values = anthrome_class_color)  +
     theme_bw() +
    theme(legend.position = NULL) +
    coord_sf(crs = st_crs("+proj=eck4"))
```


## Biome summary
```{r}
biome_summary <- an12_dgg %>% 
  left_join(st_drop_geometry(an12_dgg_inputs), by = 'id') %>%
  select(-pot_vill) %>%
  pivot_longer(-c(id, land_area, pot_veg), names_to = 'time_step', values_to = 'anthrome') %>%
    mutate(anthrome= as.factor(anthrome), pot_veg = as.factor(pot_veg)) %>%
  count(time_step, anthrome, pot_veg, wt = land_area, name = 'land_area', .drop = FALSE) %>%
  mutate(percent_land_area = land_area / total_land_area,
                  anthrome = as.numeric(as.character(anthrome)),
         pot_veg = as.numeric(as.character(pot_veg))) %>%
  left_join(anthrome_key, by = 'anthrome') %>%
  left_join(time_key, by = 'time_step') %>%
  mutate(period = case_when(year %in% c(seq(-10000, -1000, 1000), 1) ~ 'Millennia',
                            year %in% seq(100, 1700, 100) ~ 'Centuries',
                            year %in% c(seq(1710, 2010, 10), 2017) ~ 'Decades'),
         period = factor(period, c('Millennia', 'Centuries', 'Decades'))) %>%
  arrange(year, pot_veg, anthrome) %>%
    left_join(biome_key, by = c('pot_veg' = 'biome_value')) %>%
  select(time_step, pot_veg, biome, anthrome, class, percent_land_area, period, year)

write_csv(biome_summary, 'an12_dgg_summary_biomes.csv')
```


```{r, fig.height = 12, fig.width = 10}
# there are still horizontal lines from the combined biomes ... or something else
biome_summary %>%
  filter(biome != 'Ice, snow') %>%
 # mutate(pretty_biomes = str_wrap(biomes)) %>%
 ggplot(aes(as.factor(year), percent_land_area)) +
  geom_col(aes(fill = class, color = class), size = .6)+ 
   facet_grid(biome~period, scales = 'free', space = 'free_x') +
  scale_color_manual(values = anthrome_class_color, name = 'Anthrome') +
  scale_fill_manual(values = anthrome_class_color, name = 'Anthrome') +
      theme_classic() +
    scale_y_continuous(labels = scales::percent_format(accuracy = 1)) +
  scale_x_discrete(breaks = c(-10000, -5000, 1, 500, 1000, 1700, 1800, 1900, 2000),
                   labels = c('10000 ʙᴄᴇ', '5000 ʙᴄᴇ', '1 ᴄᴇ', '500 ᴄᴇ', '1000 ᴄᴇ', '1700 ᴄᴇ', '1800 ᴄᴇ', '1900 ᴄᴇ', '2000 ᴄᴇ')) +
  labs(x = 'Year', y = expression('Percent land surface')) + theme(legend.position = 'right')

ggsave('anthromes_summary_biomes.png', height = 12, width = 10)
```

# Onsets
```{r}
suppressWarnings(
  onset_seminatural <- an12_dgg %>%
    pivot_longer(-id, names_to = 'time_step', values_to = 'anthrome') %>%
  group_by(id) %>%
    filter(anthrome < 61) %>%
    left_join(time_key) %>%
  summarise(onset = min(year))
)

suppressWarnings(
  onset_used <- an12_dgg %>%
    pivot_longer(-id, names_to = 'time_step', values_to = 'anthrome') %>%
  group_by(id) %>%
    filter(anthrome < 51) %>%
    left_join(time_key) %>%
  summarise(onset = min(year))
)

onsets <- bind_rows(dplyr::select(an12_dgg_inputs, id) %>% left_join(onset_seminatural), 
                    dplyr::select(an12_dgg_inputs, id) %>% left_join(onset_used), .id = 'type') %>%
 mutate(type = if_else(type == 1, 'Onset of Seminatural Anthromes', 'Onset of Used Anthromes')) %>%
  left_join(time_key, by = c('onset' = 'year')) %>%
  st_as_sf() %>%
  st_set_crs(4326)
```

```{r}
onsets %>%
  dplyr::select(-time_step) %>%
  spread(type, onset) %>%
  write_sf('anthromes_onsets_wide.shp')
write_sf(onsets, 'anthromes_onsets.shp')
```


```{r fig.width = 10, fig.height=12}
onsets %>%
  mutate(onset = 2017 - onset) %>%
 #   st_crop(st_bbox(c(xmin = 20, xmax = 40, ymin = 30, ymax = 40))) %>% # comment out for whole world
ggplot() +
  geom_sf(aes(fill = onset, geometry = geometry), color = NA)+
  scale_fill_viridis_c(option = 'A', na.value = 'lightgrey', direction = 1, trans = 'log') +
  facet_wrap(~type, nrow = 2)  +
  theme_bw() +
    coord_sf(crs = st_crs("+proj=eck4"))
```

#Contemporary Data

```{r}
contemp <- an12_dgg %>%
  select(id, `2017AD`) %>% # should be most recent time step?
  left_join(contemp_vars, by = 'id') %>%
  left_join(anthrome_key, by = c('2017AD' = 'anthrome'))
```

```{r}
kba_summary <- contemp_vars %>%
  select(id, kba_km2) %>%
  st_drop_geometry() %>%
  left_join(an12_dgg, by = 'id') %>% 
  pivot_longer(-c(id, kba_km2), names_to = 'time_step', values_to = 'anthrome') %>%
  mutate(anthrome= as.factor(anthrome)) %>%
  count(time_step, anthrome, wt = kba_km2, name = 'var', .drop = FALSE) %>% 
  mutate(anthrome = as.numeric(as.character(anthrome))) %>%
  left_join(anthrome_key, by = 'anthrome') %>%
  left_join(time_key, by = 'time_step') %>%
  mutate(period = case_when(year %in% c(seq(-10000, -1000, 1000), 1) ~ 'Millennia',
                            year %in% seq(100, 1700, 100) ~ 'Centuries',
                            year %in%  c(seq(1710, 2010, 10), 2017) ~ 'Decades'),
         period = factor(period, c('Millennia', 'Centuries', 'Decades'))) %>%
  arrange(year, anthrome) %>%
  select(time_step, anthrome, class, var, period, year)

pa_summary <- contemp_vars %>%
  select(id, pa_km2) %>%
  st_drop_geometry() %>%
  left_join(an12_dgg, by = 'id') %>% 
  pivot_longer(-c(id, pa_km2), names_to = 'time_step', values_to = 'anthrome') %>%
  mutate(anthrome= as.factor(anthrome)) %>%
  count(time_step, anthrome, wt = pa_km2, name = 'var', .drop = FALSE) %>% 
  mutate(anthrome = as.numeric(as.character(anthrome))) %>%
  left_join(anthrome_key, by = 'anthrome') %>%
  left_join(time_key, by = 'time_step') %>%
  mutate(period = case_when(year %in% c(seq(-10000, -1000, 1000), 1) ~ 'Millennia',
                            year %in% seq(100, 1700, 100) ~ 'Centuries',
                            year %in%  c(seq(1710, 2010, 10), 2017) ~ 'Decades'),
         period = factor(period, c('Millennia', 'Centuries', 'Decades'))) %>%
  arrange(year, anthrome) %>%
  select(time_step, anthrome, class, var, period, year)

nmh4_summary <- contemp_vars %>%
  select(id, nmh_4) %>%
  st_drop_geometry() %>%
  left_join(an12_dgg, by = 'id') %>% 
  pivot_longer(-c(id, nmh_4), names_to = 'time_step', values_to = 'anthrome') %>%
  mutate(anthrome= as.factor(anthrome)) %>%
  count(time_step, anthrome, wt = nmh_4, name = 'var', .drop = FALSE) %>% 
  mutate(anthrome = as.numeric(as.character(anthrome))) %>%
  left_join(anthrome_key, by = 'anthrome') %>%
  left_join(time_key, by = 'time_step') %>%
  mutate(period = case_when(year %in% c(seq(-10000, -1000, 1000), 1) ~ 'Millennia',
                            year %in% seq(100, 1700, 100) ~ 'Centuries',
                            year %in%  c(seq(1710, 2010, 10), 2017) ~ 'Decades'),
         period = factor(period, c('Millennia', 'Centuries', 'Decades'))) %>%
  arrange(year, anthrome) %>%
  select(time_step, anthrome, class, var, period, year)

nmh34_summary <- contemp_vars %>%
  select(id, nmh_34) %>%
  st_drop_geometry() %>%
  left_join(an12_dgg, by = 'id') %>% 
  pivot_longer(-c(id, nmh_34), names_to = 'time_step', values_to = 'anthrome') %>%
  mutate(anthrome= as.factor(anthrome)) %>%
  count(time_step, anthrome, wt = nmh_34, name = 'var', .drop = FALSE) %>% 
  mutate(anthrome = as.numeric(as.character(anthrome))) %>%
  left_join(anthrome_key, by = 'anthrome') %>%
  left_join(time_key, by = 'time_step') %>%
  mutate(period = case_when(year %in% c(seq(-10000, -1000, 1000), 1) ~ 'Millennia',
                            year %in% seq(100, 1700, 100) ~ 'Centuries',
                            year %in%  c(seq(1710, 2010, 10), 2017) ~ 'Decades'),
         period = factor(period, c('Millennia', 'Centuries', 'Decades'))) %>%
  arrange(year, anthrome) %>%
  select(time_step, anthrome, class, var, period, year)
```

Summary by total land area.

```{r, fig.width=10, fig.height=10}
bind_rows(kba_summary,pa_summary, nmh34_summary, nmh4_summary, .id = 'type') %>%
  mutate(type = case_when(type == 1 ~ 'KBA',
                          type == 2 ~ 'PA',
                          type == 3 ~ 'NMH 3+4',
                          type == 4 ~ 'NMH 4')) %>%
 ggplot(aes(as.factor(year), var)) +
#  geom_area(aes(fill = class, color = class), position = 'stack') +
#  geom_col(aes(fill = class), color = 'lightgrey', size = .2)+
  geom_col(position = 'fill', aes(fill = class, color = class), size = 1)+
  geom_hline(yintercept = c(.25, .50, .75), linetype = 2, alpha = .3) +
 facet_grid(type~period, scales = 'free', space = 'free_x') +
  scale_color_manual(values = anthrome_class_color, name = 'Anthrome') +
  scale_fill_manual(values = anthrome_class_color, name = 'Anthrome') +
      theme_classic() +
  scale_y_continuous(labels = scales::percent, expand = c(0,0.02)) +
  scale_x_discrete(breaks = c(-10000, -5000, 1, 500, 1000, 1700, 1800, 1900, 2000),
                   labels = c('10000 ʙᴄᴇ', '5000 ʙᴄᴇ', '1 ᴄᴇ', '500 ᴄᴇ', '1000 ᴄᴇ', '1700 ᴄᴇ', '1800 ᴄᴇ', '1900 ᴄᴇ', '2000 ᴄᴇ')) +
  labs(x = 'Year', y = 'Percent land surface') +
  theme(legend.position = 'bottom', plot.margin = margin(.2, .2,.2, r = .5, unit = 'cm'))


ggsave('anthrome_areas_conservatino.png', width = 10, height = 10)
```



```{r}
a <- bind_rows(contemp %>%
  group_by(nmh, level) %>%
  count(wt = land_ar) %>%
  filter(!is.na(nmh)) %>%
  mutate(var = case_when(nmh == 1 ~ 'Likely Modified',
                         nmh == 2 ~ 'Potential Modified',
                         nmh == 3 ~ 'Potential Natural',
                         nmh == 4 ~ 'Likely Natural')),
  contemp %>%
  group_by(X_3_c_4, level) %>%
  count(wt = land_ar) %>%
  filter(!is.na(X_3_c_4)) %>%
  mutate(var = case_when(X_3_c_4 == 1 ~ 'Cities and Farms',
                                      X_3_c_4 == 2 ~ 'Shared Lands',
                                      X_3_c_4 == 3 ~ 'Large Wild Areas')), 
  contemp %>%
  group_by(level) %>%
  summarise(`Key Biodiversity Areas` = sum(kba_km2, na.rm = TRUE),
            `Indigenous Lands` = sum(ind_cnt, na.rm = TRUE),
            `Protected Lands` = sum(pa_km2, na.rm = TRUE),
            `All Lands` = sum(land_ar, na.rm = TRUE)) %>%
  gather(var, n, `Key Biodiversity Areas` :`All Lands`), .id = 'type') %>%
  mutate(type = factor(if_else(type == 1, 'Natural and Modified Habitats', if_else(type == 2, 'Three Global Conditions', 'Other Variables')), levels = c('Three Global Conditions', 'Natural and Modified Habitats', 'Other Variables')),
         var = factor(var, levels =  rev(c('Likely Natural', 'Potential Natural', 'Potential Modified', 'Likely Modified', 'Large Wild Areas', 'Shared Lands', 'Cities and Farms', 'All Lands',  'Indigenous Lands', 'Protected Lands', 'Key Biodiversity Areas')))) %>%
  ggplot(aes(var, n, fill = level)) +
  geom_col(position = 'fill') +
  scale_fill_manual(values = anthrome_level_color, name = NULL) +
       scale_y_continuous(labels = scales::percent_format(accuracy = 1)) +
  facet_wrap(~type, ncol = 1, scales = 'free_y') +
    labs(y = 'Percent total in each anthrome level', x = NULL) +
  coord_flip() +
  theme_classic() +
    theme( axis.line.y = element_blank(),  axis.ticks.y = element_blank(), panel.grid.major.y = element_blank(), panel.grid.minor = element_blank(), strip.background = element_blank())
  
a
```


```{r}
b <- contemp %>%
  select(id, level, hfp_max, v_thr, v_rich) %>%
  gather(key, value, hfp_max:v_rich) %>%
  mutate(key = if_else(key == 'hfp_max', 'Human Footprint (max)', if_else(key == 'v_rich', 'Vertebrate Species Richness', 'Threatened Vertebrate Species Richness'))) %>%
  ggplot(aes(level, value, fill = level)) +
  geom_boxplot(outlier.size = .1, outlier.alpha = .05, lwd = .3) +
  facet_wrap(~key, scales = 'free_x', ncol = 1) +
  theme_classic() +
  scale_fill_manual(values = anthrome_level_color, name = NULL) +
  labs( x = NULL, y = 'Distribution across anthrome levels') +
  theme(axis.line.y = element_blank(), axis.ticks.y = element_blank(), strip.background = element_blank(), axis.text.y = element_blank(), legend.position = 'none', panel.grid.minor = element_blank(), panel.grid.major.y = element_blank())  +
  coord_flip()
#b <- contemp %>%
#  group_by(landsuit, level) %>%
#  count(wt = land_ar) %>%
#  filter(!is.na(landsuit)) %>%
#  ggplot(aes(landsuit, n, fill = level)) +
#  geom_col(position = 'fill') +
#  scale_fill_manual(values = anthrome_level_color, name = 'Anthrome level') +
#  coord_flip() +
#      scale_y_continuous(labels = scales::percent_format(accuracy = 1)) +
#    labs(y = 'Percent area in each anthrome', x = 'Suitability for rainfed agriculture') +
#  theme_minimal()
```


```{r, fig.width = 10, fig.asp = 2/3}
((a | b ) + plot_layout(guides = 'collect')) / e  + plot_layout(heights = c(2, 1)) + plot_annotation(tag_levels = 'A')

ggsave('contemp_summary_levels.png', width = 10,height = 10 * 2/3)
```

### anthrome classes
```{r fig.width=10, fig.height = 6}
e <- contemp %>%
  group_by(class) %>%
  summarise(protected = sum(pa_km2, na.rm = TRUE),
            key_bio = sum(kba_km2, na.rm = TRUE),
            food_cal = sum(food_cal, na.rm = TRUE),
            v_thr = sum(v_thr, na.rm = TRUE),
            v_rich = sum(v_rich, na.rm = TRUE),
            hfp_mx = sum(hfp_max, na.rm = TRUE),
            indigenous = sum(ind_cnt, na.rm = TRUE),
            all_land = sum(land_area, na.rm = TRUE)) %>%
  gather(variable, value, protected:all_land) %>%
  ggplot(aes(x = variable, y = value, fill = class)) +
  geom_col(position = 'fill') +
  scale_fill_manual(values = anthrome_class_color, name = 'Anthrome class') +
    scale_y_continuous(labels = scales::percent_format(accuracy = 1)) +
  coord_flip() +
  labs(y = 'Percent total in each anthrome') +
  theme_minimal()

f <- contemp %>%
  group_by(landsuit, class) %>%
  count(wt = land_area) %>%
  filter(!is.na(landsuit)) %>%
  ggplot(aes(landsuit, n, fill = class)) +
  geom_col(position = 'fill') +
  scale_fill_manual(values = anthrome_class_color, name = 'Anthrome class') +
  coord_flip() +
      scale_y_continuous(labels = scales::percent_format(accuracy = 1)) +
    labs(y = 'Percent area in each anthrome', x = 'Suitability for rainfed agriculture') +
  theme_minimal()

g <- contemp %>%
  group_by(nmh, class) %>%
  count(wt = land_area) %>%
  filter(!is.na(nmh)) %>%
  ggplot(aes(nmh, n, fill = class)) +
  geom_col(position = 'fill') +
  scale_fill_manual(values = anthrome_class_color, name = 'Anthrome class') +
  coord_flip() +
       scale_y_continuous(labels = scales::percent_format(accuracy = 1)) +
    labs(y = 'Percent area in each anthrome', x = 'Natural and Modified Habitat') +
  theme_minimal()

h <- contemp %>%
  group_by(X.3_cond_v4, class) %>%
  count(wt = land_area) %>%
  filter(!is.na(X.3_cond_v4)) %>%
  ggplot(aes(X.3_cond_v4, n, fill = class)) +
  geom_col(position = 'fill') +
  scale_fill_manual(values = anthrome_class_color, name = 'Anthrome class') +
  coord_flip() +
       scale_y_continuous(labels = scales::percent_format(accuracy = 1)) +
    labs(y = 'Percent area in each anthrome', x = 'Three Global Conditions') +
  theme_minimal()

e+ f + g+h + plot_layout(guides = "collect") & theme(legend.position = "bottom")

ggsave('contemp_summary_class.png', width = 10,height = 7)
```


## maps


```{r}
contemp_vars %>%
st_crop(st_bbox(c(xmin = 40, xmax = 70, ymin = 20, ymax = 40))) %>% # comment out for whole world
  ggplot() +
  geom_sf(aes(fill = (0.2 >= pa_km2 & pa_km2 > 0)), color = NA) +
  scale_fill_viridis_d() +
  coord_sf(crs = st_crs("+proj=eck4"))

contemp_vars %>%
st_crop(st_bbox(c(xmin = -100, xmax = -50, ymin = 0, ymax = 20))) %>% # comment out for whole world
  ggplot() +
  geom_sf(aes(fill = ind_cnt), color = NA) +
  scale_fill_viridis_c() +
  coord_sf(crs = st_crs("+proj=eck4"))

contemp_vars %>%
st_crop(st_bbox(c(xmin = -100, xmax = -50, ymin = 0, ymax = 20))) %>% # comment out for whole world
  ggplot() +
  geom_sf(aes(fill = ind_cnt>50), color = NA) +
  scale_fill_viridis_d() +
  coord_sf(crs = st_crs("+proj=eck4"))

contemp_vars %>%
st_crop(st_bbox(c(xmin = -100, xmax = -50, ymin = 0, ymax = 20))) %>% # comment out for whole world
  ggplot() +
  geom_sf(aes(fill = ind_cnt>0), color = NA) +
  scale_fill_viridis_d() +
  coord_sf(crs = st_crs("+proj=eck4"))
```
```{r}
contemp_vars %>%
st_crop(st_bbox(c(xmin = -100, xmax = -50, ymin = 0, ymax = 20))) %>% # comment out for whole world
  ggplot() +
  geom_sf(aes(fill = pa_km2), color = NA) +
  scale_fill_viridis_c() +
  coord_sf(crs = st_crs("+proj=eck4"))

contemp_vars %>%
st_crop(st_bbox(c(xmin = -100, xmax = -50, ymin = 0, ymax = 20))) %>% # comment out for whole world
  ggplot() +
  geom_sf(aes(fill = pa_km2>50), color = NA) +
  scale_fill_viridis_d() +
  coord_sf(crs = st_crs("+proj=eck4"))

contemp_vars %>%
st_crop(st_bbox(c(xmin = -100, xmax = -50, ymin = 0, ymax = 20))) %>% # comment out for whole world
  ggplot() +
  geom_sf(aes(fill = pa_km2>0), color = NA) +
  scale_fill_viridis_d() +
  coord_sf(crs = st_crs("+proj=eck4"))
```


# Regression

Anthrome levels
```{r}
library(nnet)
calc_aic <- function(predictand, predictor){
  as.formula(paste(predictand, '~', predictor)) %>%
    glm(family = poisson(), data = reg_dat34) %>% 
    AIC
}
calc_aic2 <- function(predictand, predictor){
  as.formula(paste(predictand, '~', predictor)) %>%
    glm(family = binomial, data = reg_dat34) %>% 
    AIC
}
calc_aic3 <- function(predictand, predictor){
  as.formula(paste(predictand, '~', predictor)) %>%
    multinom(data = regression_dat) %>% 
    AIC
}
```

```{r}
regression_dat <- an12_dgg %>%
  pivot_longer(-id, names_to = 'time', values_to = 'anthrome') %>%
  left_join(anthrome_key) %>%
  dplyr::select(-anthrome, -level, -type) %>%
  pivot_wider(names_from = time, values_from = class) %>%
  left_join(contemp_vars, by = 'id') %>%
  na.omit # shouldn't have to do this last step!

reg_dat34 <- regression_dat %>% filter(nmh_34 > 0.5)
reg_dat4 <- regression_dat %>% filter(nmh_4 > 0.5)


test_aic_class <- expand_grid(time_step = time_steps_centuries,
                   predictands = c('hfp_max', 'v_thr', 'v_rich')) %>%
  mutate(predictors = paste0('`', time_step, '`'),
         aic = map2_dbl(predictands, predictors, calc_aic)) %>%
  left_join(time_key)

test_aic_class2 <- expand_grid(time_step = time_steps_centuries,
                   predictands = c('kba50', 'ind50', 'pa50')) %>%
  mutate(predictors = paste0('`', time_step, '`'),
         aic = map2_dbl(predictands, predictors, calc_aic2)) %>%
  left_join(time_key)

test_aic_class3 <- expand_grid(time_step = time_steps_centuries,
                   predictands = c('kba', 'ind', 'pa')) %>%
  mutate(predictors = paste0('`', time_step, '`'),
         aic = map2_dbl(predictands, predictors, calc_aic2)) %>%
  left_join(time_key)

test_aic_class3 <- expand_grid(time_step = time_steps_centuries,
                   predictands = c('kba50', 'ind50', 'pa50')) %>%
  mutate(predictors = paste0('`', time_step, '`'),
         aic = map2_dbl(predictands, predictors, calc_aic2)) %>%
  left_join(time_key)

#test_aic_class3 <- expand_grid(time_step = time_steps_centuries,
#                   predictands = c('`2017AD`')) %>%
#  mutate(predictors = paste0('`', time_step, '`'),
#         aic = map2_dbl(predictands, predictors, calc_aic3)) %>%
#  left_join(time_key)

preds_order <- bind_rows(test_aic_class, test_aic_class2) %>%
  group_by(predictands) %>%
  mutate(aic_scaled = scales::rescale(aic)) %>%
  filter(aic_scaled == min(aic_scaled)) %>%
  arrange(year) %>%
  pull(predictands)
  
e <- bind_rows(test_aic_class, test_aic_class2) %>%
  mutate(vars = factor(predictands, levels = rev(c('v_rich', 'v_thr', 'kba50', 'hfp_max', 'pa50',  'ind50')))) %>%
  group_by(vars) %>%
  mutate(aic_scaled = scales::rescale(aic)) %>%
  ggplot(aes(as.factor(year), vars, fill = aic_scaled), color = 'white') +
  geom_tile() +
  scale_fill_viridis_c(direction = -1, name = 'Scaled AIC', breaks = c(.05, .95), labels = c('Best', 'Worst')) +
  theme_classic() +
  scale_y_discrete(labels = c('Indigenous Lands', 'Protected Lands', 'Human Footprint (max)', 'Key Biodiversity Areas', 'Threatened Species Richness', 'Species Richness')) +
  scale_x_discrete(breaks = c(1, 500, 1000, 1500, 2000),
                   labels = c('1 ᴄᴇ', '500 ᴄᴇ', '1000 ᴄᴇ', '1500 ᴄᴇ', '2000 ᴄᴇ'))  +
  labs(x = 'Predictor Year', y = NULL)
e
ggsave(e, 'anthrome_legacies34.png', height = 3, width = 6)
```

```{r}
bind_rows(test_aic_class, test_aic_class2) %>%
  group_by(predictands) %>%
  mutate(aic_scaled = scales::rescale(aic)) %>%
  ggplot(aes(year, aic)) +
  geom_line() +
  geom_point() +
  facet_wrap(~predictands, scales = 'free_y') +
  theme_minimal()
```



```{r}
bllep <- expand_grid(time_step = time_steps_centuries,
                   predictands = c('kba', 'ind', 'pa')) %>%
  mutate(predictors = paste0('`', time_step, '`'),
         gof = map2_dbl(predictands, predictors, glemp)) %>%
  left_join(time_key)
glemp <- function(predictand, predictor){
  mod <- as.formula(paste(predictand, '~', predictor)) %>%
    glm(family = binomial, data = regression_dat)
  
    with(summary(mod), 1 - deviance/null.deviance)
}


bllep%>%
  group_by(predictands) %>%
  mutate(aic_scaled = scales::rescale(aic),
         aic_test = aic / min(aic)) %>%
  ggplot(aes(as.factor(year), predictands, fill = aic), color = 'white') +
  geom_tile() +
  scale_fill_viridis_c(direction = 1) +
  theme_classic() +
  scale_x_discrete(breaks = c(1, 500, 1000, 1500, 2000),
                   labels = c('1 ᴄᴇ', '500 ᴄᴇ', '1000 ᴄᴇ', '1500 ᴄᴇ', '2000 ᴄᴇ'))  +
  coord_fixed()
```



```{r}
hist(contemp_vars$ind_cnt)
hist(contemp_vars$pa_km2)
hist(contemp_vars$kba_km2)
hist(contemp_vars$max)
hist(contemp_vars$v_rich)
hist(contemp_vars$v_thr)
hist(contemp_vars$nmh_34)
hist(contemp_vars$nmh_4)
```
```{r}
sum(contemp_vars$nmh_4 == 1)
sum(contemp_vars$nmh_34 == 1);sum(contemp_vars$nmh_34 > .99)

```



```{r}
# check out some regressions
m1 <- glm(v_thr ~ `1500AD`, family = poisson, data = regression_dat)
with(summary(m1), 1 - deviance/null.deviance)

m2 <- glm(v_thr ~ `2000AD`, family = poisson, data = regression_dat)
with(summary(m2), 1 - deviance/null.deviance)

lm(max ~ `1900AD`, data = regression_dat) %>% summary
lm(max ~ `2000AD`, data = regression_dat) %>% summary

```



```{r}
m1 <- glm(pa_km2 > 0 ~ `2000AD`, family = binomial, data = regression_dat)
m2 <- glm(pa_km2 > 0 ~ `600AD`, family = binomial, data = regression_dat)
m3 <- glm(pa_km2 > 1 ~ `2000AD`, family = binomial, data = regression_dat)
m4 <- glm(pa_km2 > 1 ~ `600AD`, family = binomial, data = regression_dat)
AIC(m1, m2);AIC(m3, m4)

t1 <- regression_dat %>%
  modelr::add_predictions(m1, var = 'pred2000', type = 'response') %>%
    modelr::add_predictions(m2, var = 'pred600', type = 'response')


t1 %>% select(pred2000, pred600, geometry) %>%
  st_as_sf %>%
  st_crop(st_bbox(c(xmin = 0, xmax = 60, ymin = 20, ymax = 60))) %>% # comment out for whole world
  gather(key, value, pred2000:pred600) %>%
  ggplot()+
  geom_sf(aes(fill = value), color = NA) +
  facet_wrap(~key) +
  scale_fill_viridis_c() +
  coord_sf(crs = st_crs("+proj=eck4"))


summary(m2);summary(m1)
```

```{r}
t1 %>% st_as_sf %>%
  st_crop(st_bbox(c(xmin = 0, xmax = 60, ymin = 20, ymax = 60))) %>% # comment out for whole world
  ggplot()+
  geom_sf(aes(fill = pa_km2), color = NA) +
  scale_fill_viridis_c() +
  coord_sf(crs = st_crs("+proj=eck4"))

t1 %>% st_as_sf %>%
  st_crop(st_bbox(c(xmin = 0, xmax = 60, ymin = 20, ymax = 60))) %>% # comment out for whole world
  ggplot()+
  geom_sf(aes(fill = pa_km2 >0), color = NA) +
  scale_fill_viridis_d() +
  coord_sf(crs = st_crs("+proj=eck4"))

t1 %>% st_as_sf %>%
  st_crop(st_bbox(c(xmin = 0, xmax = 60, ymin = 20, ymax = 60))) %>% # comment out for whole world
  ggplot()+
  geom_sf(aes(fill = pa_km2 >10), color = NA) +
  scale_fill_viridis_d() +
  coord_sf(crs = st_crs("+proj=eck4"))

t1 %>% st_as_sf %>%
  st_crop(st_bbox(c(xmin = 0, xmax = 30, ymin = 40, ymax = 60))) %>% # comment out for whole world
  ggplot()+
  geom_sf(aes(fill = ind_cnt), color = NA) +
  scale_fill_viridis_d() +
  coord_sf(crs = st_crs("+proj=eck4"))
```



```{r}
library(glmnet)
regression_mat <-  model.matrix(~ .-1,  dplyr::select(regression_dat, any_of(time_steps_centuries)))
# this doesn't treat the predictand as a factor
test_mod <- cv.glmnet(regression_mat, pull(regression_dat, kba50), family = 'binomial', intercept = FALSE, standardize = FALSE)
test_mod
plot(test_mod)

coef(test_mod, s= "lambda.1se")

```



# Treemap

```{r, fig.width = 10, fig.height=4.5}
library(treemapify)

anthromes_summary %>%
  filter(year %in% c(1, 1000, 2000)) %>%
  mutate(year = paste(year, 'CE')) %>%
  ggplot(aes(area = as.numeric(area), fill  = class, label = class, subgroup = level)) +
  geom_treemap() +
  geom_treemap_subgroup_border(color = 'black') +
    facet_wrap(~year) +
  scale_fill_manual(values = anthrome_class_color, name = 'Anthrome')  +
  theme(legend.position  = 'bottom') +
  geom_treemap_subgroup_text(reflow = TRUE, fontface = 'italic', alpha = .8)

ggsave('treeplot1.png', width = 10, height = 4.5)
```

```{r, fig.height=10, fig.width = 10}
anthromes_summary %>%
  filter(year %in% c(1700, 1800, 1900, 2000)) %>%
  mutate(year = paste(year, 'CE')) %>%
  ggplot(aes(area = as.numeric(area), fill  = class, label = class, subgroup = level)) +
  geom_treemap() +
  geom_treemap_subgroup_border(color = 'black') +
    facet_wrap(~year) +
  scale_fill_manual(values = anthrome_class_color, name = 'Anthrome')  +
  theme(legend.position  = 'bottom') +
  geom_treemap_subgroup_text(reflow = TRUE, fontface = 'italic', alpha = .8)

ggsave('treeplot2.png', width = 10, height = 10)
```

# Alluvial plots

```{r}
library(ggalluvial)
test <- anthromes_dat %>% 
  filter(year %in% c(0, 500, 1000, 1500, 2000)) %>%
  left_join(anthrome_key)
  
ggplot(test, aes(x = as.factor(year), stratum = level, fill = level, label = level, alluvium = interaction(x,y), y = as.numeric(area))) +
    geom_flow() +
  geom_stratum(alpha = .5) +
  scale_fill_manual(values = anthrome_level_color, name = 'Anthrome')  +
  theme(legend.position  = 'bottom') +
  geom_text(stat = 'stratum', size = 3) +
  theme_minimal()
```


# Correlograms

```{r}
library(corrplot)
periods <- anthromes_summary %>%
  group_by(period) %>%
  nest

periods %>%
  mutate(data = map(data, ~  select(., year, area, class) %>%
  pivot_wider(names_from = class, values_from = area) %>%
  select(-year) %>%
    cor)) %>%
  pull(data) %>%
  map(~ corrplot(., method = 'color', type = 'lower'))


cor.mtest <- function(mat, ...) {
    mat <- as.matrix(mat)
    n <- ncol(mat)
    p.mat<- matrix(NA, n, n)
    diag(p.mat) <- 0
    for (i in 1:(n - 1)) {
        for (j in (i + 1):n) {
            tmp <- cor.test(mat[, i], mat[, j], ...)
            p.mat[i, j] <- p.mat[j, i] <- tmp$p.value
        }
    }
  colnames(p.mat) <- rownames(p.mat) <- colnames(mat)
  p.mat
}

test2%>%
  cor %>%
  corrplot(method = 'color', type = 'lower', order = 'hclust', p.mat = cor.mtest(test2), sig.level = 0.01, insig = 'blank')
```

