---
title: "anthromes_classification"
author: "Nick Gauthier"
date: "7/20/2020"
output: html_document
---


```{r setup}
library(stars)
library(dplyr)
```


```{r}
hyde_inputs <- list.files('data/raw_data/hyde_output', full.names = TRUE) %>%
  read_stars %>%
  setNames(c('conv_rangeland', 'crops', 'grazing', 'rice', 'pasture', 'pop', 'rangeland', 'irrigation', 'urban')) %>%
  mutate(graze2 = grazing,
         grazing = conv_rangeland + rangeland + pasture,
         used = urban + crops + grazing)

fixed_inputs <- list.files('data/raw_data/fixed_input', full.names = TRUE) %>%
  .[c(1, 4)] %>%# remove greg28_cr.asc, iso_cr.asc
  read_stars() %>%
  setNames(c('biome', 'area')) %>%
  mutate(trees = if_else(biome <= 8, TRUE, FALSE)) # Define the non-woody classes in the BIOME map
```

```{r}
# divide hyde inputs by land area to get coverage proportion
dat <- hyde_inputs / fixed_inputs['area']

# population is already a density, so replace with the original values
dat$pop <- hyde_inputs$pop
```



```{r}
test <- dat %>%
  c(fixed_inputs) %>%
  as_tibble() %>% 
filter(!is.na(urban)) %>%
  mutate(anthrome = case_when(
      urban >= 0.2 | pop >= 2500 ~ 11,
      #pop >= 100 & pot_vill == FALSE ~ 12,
      pop >= 100 & rice >= 0.2 ~ 21,
      pop >= 100 & irrigation >= 0.2 ~ 22,
      pop >= 100 & crops >= 0.2 ~ 23,
      pop >= 100 & grazing >= 0.2 ~ 24,
      pop >= 100 ~ 12,
      crops >= 0.2 & pop >= 10 & pop < 100 & irrigation >= 0.2 ~ 31,
      crops >= 0.2 & pop >= 10 & pop < 100 ~ 32,
      crops >= 0.2 & pop >= 1 & pop < 10 ~ 33,
      crops >= 0.2 & pop > 0 & pop < 1 ~ 34,
      grazing >= 0.2 & pop >= 10 & pop < 100 ~ 41,
      grazing >= 0.2 & pop >= 1 & pop < 10 ~ 42,
      grazing >= 0.2 & pop > 0 & pop < 1 ~ 43,
      trees & pop >= 10 & pop < 100 ~ 51,
      trees & pop >= 1 & pop < 10 ~ 52,
      trees & pop > 0 & pop < 1 & used < 0.2 ~ 53,
      trees & pop > 0 & pop < 1 & used >= 0.2 & crops >= grazing ~ 34,
      trees & pop > 0 & pop < 1 & used >= 0.2 & crops < grazing ~ 43,
      pop > 0 & !trees & used < 0.2 ~ 54,
      pop > 0 & !trees & used >= 0.2 & crops >= grazing ~ 34,
      pop > 0 & !trees & used >= 0.2 & crops < grazing ~ 43,
      used >= 0.2 & crops >= 0.2 ~ 34,  # in python code but not paper
      used >= 0.2 & grazing >= 0.2 ~ 43,  # in python code but not paper
      used >= 0.2 & crops >= grazing ~ 34,
      used >= 0.2 & crops < grazing ~ 43,
      area > 0 & biome != 15 & trees ~ 61,
      area > 0 & biome != 15 & !trees ~ 62,
      area > 0 & biome == 15 & used > 0 ~ 62, # in python code but not paper
      area > 0 & biome == 15 ~ 63,
      TRUE ~ 70)
      ) %>%
  #select(x, y, anthrome) %>%
  mutate_at(c('x','y'), round, 5)
```


```{r}
test2 <- readRDS('anthromes_dat') %>%
  filter(year == 2000) %>%
  mutate_at(c('x','y'), round, 5)
```

```{r}
left_join(test2, test) %>%
  mutate(test = value == anthrome) %>%
  ggplot(aes(x, y, fill = test)) +
  geom_raster()
```

```{r}
left_join(test2, test, by = c("x", "y")) %>%
  mutate(test = value == anthrome) %>%
  filter(test == FALSE)
```


```{r}
left_join(test2, test) %>%
  filter(value != anthrome) %>%
  group_by(value, anthrome) %>%
  count %>%
  arrange(-n)
```

```{r}
left_join(test2, test, by = c("x", "y")) %>%
  mutate(test = value == anthrome) %>%
  filter(test == FALSE) %>%
  filter(value == 43) %>%
  select(value, anthrome, pop, used, crops, grazing) %>%
  mutate(grazing <= 0.2) %>%
  pull(grazing) %>%
  sprintf("%.54f",.)  


0.2 >= 0.2


sprintf()
sprintf("%.54f",0.2)  
```

```{r}
left_join(test2, test) %>%
  filter(value != anthrome) %>%
  group_by(value, anthrome) %>%
  count %>%
  ungroup() %>%
  summarise(sum(n))
  
```

