---
title: "reprojection"
author: "Nick Gauthier"
date: "7/23/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(raster)
library(sf)
library(exactextractr)
library(fasterize)
library(tidyverse)
devtools::load_all()
```



```{r}
land_area <- raster('data/raw_data/fixed_input/maxln_cr.asc')
```

```{r}
dgg_land <- read_sf('data/raw_data/l12_ISEAH_dgg.shp/l12_ISEA3H_dgg.shp') %>%
  mutate(land_area = exact_extract(land_area, ., 'sum')) %>%
  filter(land_area > 0) %>%
  tibble::remove_rownames()
```

```{r}
write_sf(dgg_land, 'l12_ISEA3H_dgg_land.shp')
```


## all files
```{r}
dgg_land <- read_sf('l12_ISEA3H_dgg_land.shp')
dgg_ids <- dgg_land$id

saveRDS(dgg_ids, 'dgg_ids')
```

Loop through each variable name, import the HYDE rasters from each year, brick, and extract by dgg cells.
```{r}
hyde_names <- c('cropland', 'grazing', 'ir_rice', 'popc', 'tot_irri', 'uopp')

hyde2dgg <- function(hyde_varname, hyde_path){
  suppressWarnings(
    list.files(hyde_path, recursive = TRUE, full.names = TRUE) %>%
      str_subset(., hyde_varname) %>% 
      map(raster) %>%
      brick %>%
      `crs<-`(value = '+proj=longlat +datum=WGS84 +no_defs +ellps=WGS84 +towgs84=0,0,0') %>%
  exact_extract(dgg_land, 'sum')
  )
}

hyde_dgg <- hyde_names %>%
  map(hyde2dgg, '~/Downloads/baseline/zip') %>%
  bind_cols()
```

```{r}
saveRDS(hyde_dgg, 'hyde_dgg')
```


```{r}
land_area_rast <- raster('data/raw_data/supporting_5m_grids/maxln_cr.tif')
pot_veg_rast <- raster('data/raw_data/supporting_5m_grids/potveg15.tif')
pot_vill_rast <- raster('data/raw_data/supporting_5m_grids/potvill20.tif')
plot(pot_veg <= 8)
```

```{r}
fixed_inputs <- dgg_land %>%
  mutate(area = exact_extract(land_area_rast, ., 'sum'),
         pot_veg = exact_extract(pot_veg_rast, ., 'mode'),
         pot_vill = exact_extract(pot_vill_rast, ., 'mode')) %>%
  mutate(trees = pot_veg <= 8) %>% 
  select(area:trees) %>%
  st_drop_geometry() %>%
  rownames_to_column('id')
```

does the tree map match what you get by thresholding the biomes later?



```{r}
write_csv(fixed_inputs, 'fixed_inputs.csv')
```

```{r}
dgg_ids <- readRDS('dgg_ids')
fixed_inputs <- read_csv('fixed_inputs.csv') %>%
  mutate(id = dgg_ids)

hyde_dgg <- readRDS('hyde_dgg')

hyde_names_grepl <- str_c('cropland', 'grazing', 'ir_rice', 'popc', 'tot_irri', 'uopp', sep = '|')

var_names <- names(hyde_dgg) %>%
  str_extract(hyde_names_grepl)

time_steps <- names(hyde_dgg) %>%
  str_sub(start = str_length(var_names) + 5) %>%
  str_remove('_')

new_names <- paste(var_names, time_steps, sep = '.')

anthromes_dgg <- hyde_dgg %>%
    setNames(new_names) %>%
  mutate(id = dgg_ids) %>%
  split(1:200) %>%
  map_dfr(~gather(., key = 'name', value = 'value', -id) %>%
  separate(name, into = c('var', 'time_step'), sep = '[.]') %>%
  spread(var, value) %>%
  left_join(fixed_inputs, by = 'id') %>%
  mutate(crops = cropland / area,
            grazing = grazing / area,
            rice = ir_rice / area,
            pop = popc / area,
            irrigation = tot_irri / area,
            urban = uopp / area,
            used = urban + crops + grazing,
            .keep = 'unused') %>%
  anthromes_classify()) #%>%
## necassary to save ram, but not if run on cluster
write_csv(anthromes_dgg, 'anthromes_dgg2.csv')
gc()
read_csv('anthromes_dgg2.csv') %>%
  mutate(time_step = factor(time_step, levels = time_key$time_step)) %>%
  arrange(id, time_step) %>%
  spread(time_step, anthrome) %>%
  write_csv('anthromes_dgg.csv')
```



```{r}
write_csv(anthromes_dgg, 'anthromes_dgg.csv')
```

```{r}
anthromes_dgg <- read_csv('anthromes_dgg.csv', col_types = cols(.default = 'i'))
```

```{r}
anthromes_dgg_shp <- anthromes_dgg %>%
  mutate(geometry = dgg_land$geometry) %>%
  st_as_sf() %>%
  st_set_crs(4326)
  
write_sf(anthromes_dgg_shp, 'anthromes_dgg.shp')
```

```{r}
ggplot(anthromes_dgg_shp) +
  geom_sf(aes(fill = as.factor(`1200AD`)), color = NA, lwd = .1)
```


# Create final masks and grids
```{r, eval = FALSE}
dgg_land <- read_sf('l12_ISEA3H_dgg_land.shp')

#this is erles mask
land_mask <- read_sf('../an12_dgg_cells.shp') %>%
  filter(DGG_status == 3) %>%
  pull(ANL12_ID)

fixed_inputs <- read_csv('fixed_inputs.csv') %>%
  mutate(id = dgg_land$id)

an12_fixed_inputs <- dgg_land %>% 
  filter(id %in% land_mask) %>% 
  left_join(fixed_inputs) %>%
  select(id, land_area, pot_veg, pot_vill, geometry) %>%
    st_set_crs(4326)

an12_dgg_inputs <- read_sf('an12_dgg_inputs.shp')
an12_dgg <- read_csv('anthromes_dgg.csv') %>%
  filter(id %in% an12_dgg_inputs$id)%>%
  pivot_longer(-id, names_to = 'time_step', values_to = 'anthrome') %>%
  left_join(time_key) %>%
  #filter(year <= 2000) %>%
  arrange(id, year, anthrome) %>%
  mutate(id = as.integer(id), anthrome = as.integer(anthrome)) %>%
  select(-year) %>%
  pivot_wider(names_from = time_step, values_from = anthrome)

write_sf(an12_fixed_inputs, 'an12_dgg_inputs.shp')
write_csv(an12_dgg, 'an12_dgg.csv')


an12_dgg_inputs %>% dplyr::select(id) %>%
  left_join(an12_dgg) %>%
  write_sf('an12_dgg.shp')
```
add regions

```{r}
regions_dgg <- raster::raster('../simple_regions.tif') %>%
  exact_extract(an12_dgg_inputs, 'mode')

an12_dgg_inputs %>%  st_set_crs(4326) %>% mutate(region = regions_dgg) %>% left_join(region_key) %>%
  select(-region) %>%
  write_sf('an12_dgg_inputs.shp')
```

# DGG generation from analysis script
```{r}
# construct the DGG
dggs <- dgconstruct(res=12)

#save the DGG
dgearthgrid(dggs, frame = TRUE, wrapcells = FALSE, savegrid =  "./l12_ISEA3H_dgg.shp")

dgg <- dgconstruct(res = 12) %>%
  dgearthgrid(frame = TRUE, wrapcells = FALSE, savegrid = 'dgg_l12.shp')


grid <- dgconstruct(res = 7) %>%
  dgearthgrid(frame = FALSE, wrapcells = FALSE) %>%
  st_as_sf() %>%
  mutate(id = 1:n()) %>%
  st_wrap_dateline(options = c("WRAPDATELINE=YES", "DATELINEOFFSET=30")) %>%
  .[land_mask, ]

 #%>% st_set_crs('+proj=isea')
plot(grid)
```

```{r}
dgg12 <- read_sf('data/raw_data/l12_ISEAH_dgg.shp/l12_ISEA3H_dgg.shp')

dgg12 <- st_set_crs(dgg12 , st_crs(anthromes))
```
