---
title: "reprojection"
author: "Nick Gauthier"
date: "7/23/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(raster)
library(sf)
library(exactextractr)
library(fasterize)
library(tidyverse)
```



```{r}
crops <- raster('data/raw_data/hyde_output/cropland2000AD.asc')
land_area <- raster('data/raw_data/fixed_input/maxln_cr.asc')

crop_prop <- crops / land_area
land_frac <- land_area / area(land_area)
```

```{r}
dgg_land <- read_sf('data/raw_data/l12_ISEAH_dgg.shp/l12_ISEA3H_dgg.shp') %>%
  mutate(land_area = exact_extract(land_area, ., 'sum')) %>%
  filter(land_area > 0) %>%
  tibble::remove_rownames()
```

```{r}
write_sf(dgg_land, 'l12_ISEA3H_dgg_land.shp')
```


```{r}
#cellStats(land_area, 'sum', na.rm = TRUE)
```



```{r}
test <- brick(crops, land_area) %>%
  exact_extract(dgg, 'sum')
```


```{r]}
dat <- dgg %>%
  mutate(crops_sum = exact_extract(crops, ., 'sum'),
         crop_prop = exact_extract(crop_prop, ., 'mean'),
         land_area = exact_extract(land_area, ., 'sum'),
         land_frac = exact_extract(land_frac, ., 'mean'))
```

```{r}
```

```{r}
dat2 <- st_drop_geometry(dat) %>%
  filter(land_area> 0)
```


```{r}
ggplot(dat) +
  geom_sf(aes(fill = crops), color = NA)
```

```{r}
crops_real <- as.data.frame(crops, na.rm = TRUE) %>%
  pull(cropland2000AD) %>%
  sum

t2 <- as.data.frame(land_area, na.rm = TRUE) %>%
  pull(maxln_cr) %>%
  sum
```

```{r}
dat2 %>%
  summarise(crops_sum = sum(crops_sum, na.rm = TRUE),
            crops_mean1 = sum(crop_prop * land_area, na.rm = TRUE),
            crops_mean2 = sum(crop_prop * H_AREA_K_1 * land_frac, na.rm = TRUE)) %>%
  mutate_all(~(crops_real-.)/crops_real * 100)
```

```{r}
test3 <- exact_extract(crops, dgg, 'weighted_mean', weights=land_area)
```




```{r}
crop_prop_1km <- disaggregate(crops, 10)
```

```{r, warning=FALSE}
dgg_rast <- fasterize(dgg, crop_prop_1km, field = 'L1_ID')

dgg_rast_dat <- as.data.frame(brick(dgg_rast, crop_prop_1km), xy = TRUE, na.rm = TRUE)
```

## all files
```{r}
dgg_land <- read_sf('l12_ISEA3H_dgg_land.shp')
dgg_ids <- dgg_land$id
```


```{r}
hyde_names <- c('cropland', 'grazing', 'ir_rice', 'popc', 'tot_irri', 'uopp')

hyde2dgg <- function(hyde_varname, hyde_path){
  suppressWarnings(
    list.files(hyde_path, recursive = TRUE, full.names = TRUE) %>%
      str_subset(., hyde_varname) %>% 
      map(raster) %>%
      brick %>%
      `crs<-`(value = '+proj=longlat +datum=WGS84 +no_defs +ellps=WGS84 +towgs84=0,0,0') %>%
  exact_extract(dgg_land, 'sum')
  )
}


hyde_dgg <- hyde_names %>%
  map(hyde2dgg, '~/Downloads/HYDE/hyde32_output')
```

```{r}
saveRDS(hyde_dgg, 'hyde_dgg')
```



```{r}
land_area_rast <- raster('data/raw_data/supporting_5m_grids/maxln_cr.tif')
pot_veg_rast <- raster('data/raw_data/supporting_5m_grids/potveg15.tif')
pot_vill_rast <- raster('data/raw_data/supporting_5m_grids/potvill20.tif')
plot(pot_veg <= 8)
```

```{r}
fixed_inputs <- dgg_land %>%
  mutate(area = exact_extract(land_area_rast, ., 'sum'),
         pot_veg = exact_extract(pot_veg_rast, ., 'mode'),
         pot_vill = exact_extract(pot_vill_rast, ., 'mode')) %>%
  mutate(trees = pot_veg <= 8) %>% 
  select(area:trees) %>%
  st_drop_geometry() %>%
  rownames_to_column('id')
```

does the tree map match what you get by thresholding the biomes later?



```{r}
write_csv(fixed_inputs, 'fixed_inputs.csv')
```

```{r}
fixed_inputs <- read_csv('fixed_inputs.csv') %>%
  mutate(id = dgg_ids)
```



```{r}
hyde_dgg <- readRDS('hyde_dgg') %>%
  bind_cols()

hyde_names_grepl <- str_c('cropland', 'grazing', 'ir_rice', 'popc', 'tot_irri', 'uopp', sep = '|')

var_names <- names(hyde_dgg) %>%
  str_extract(hyde_names_grepl)
time_steps <- names(hyde_dgg) %>%
  str_sub(start = str_length(var_names) + 5) %>%
  str_remove('_')

new_names <- paste(var_names, time_steps, sep = '.')

anthromes_dgg <- hyde_dgg %>%
    setNames(new_names) %>%
  mutate(id = dgg_ids) %>%
  #pivot_longer(-id) %>%
  split(1:100) %>%
  map_dfr(~gather(., key = 'name', value = 'value', -id) %>%
  separate(name, into = c('var', 'time_step'), sep = '[.]') %>%
 # mutate(var = str_extract(name, hyde_names),
#         time_step =  str_sub(name, start = str_length(var) + 5),
 #        time_step = str_remove(time_step, '_')) %>% # the population files have an extra _ before the date
  #dplyr::select(-name) %>%
  #pivot_wider(names_from = var, values_from = value)
  spread(var, value) %>%
  left_join(fixed_inputs, by = 'id') %>%
  mutate(crops = cropland / area,
            grazing = grazing / area,
            rice = ir_rice / area,
            pop = popc / area,
            irrigation = tot_irri / area,
            urban = uopp / area,
            used = urban + crops + grazing,
            .keep = 'unused') %>%
  anthromes_classify()) %>%
  spread(time_step, anthrome)
```

```{r}
write_csv(anthromes_dgg, 'anthromes_dgg.csv')
```

```{r}
anthromes_dgg <- read_csv('anthromes_dgg.csv')
```

```{r}
anthromes_dgg_shp <- left_join(dgg_land, anthromes_dgg, by = 'id')
  
write_sf(anthromes_dgg_shp, 'anthromes_dgg.shp')
```

```{r}
ggplot(anthromes_dgg_shp) +
  geom_sf(aes(fill = as.factor(`1200AD`)), color = NA)
```

```{r}
library(nomclust)


set.seed(1000)
cluster_samp <- anthromes_dgg %>%
  slice_sample(prop = 0.02, weight_by = dgg_land$land_area) %>% 
  pivot_longer(-id, names_to = 'time_step', values_to = 'anthrome') %>%
  dplyr::mutate(time_step = factor(time_step, levels = time_steps_ordered)) %>%
    dplyr::arrange(id, time_step)


clusters_millennia <- cluster_samp %>%
  filter(!(time_step %in% recent_time_steps),
         time_step %in% time_steps_millennia) %>%
  pivot_wider(names_from = time_step, values_from = anthrome) %>%
  select(-id) %>%
  nomclust(prox = FALSE, measure = 've')
  
clusters_centuries <- cluster_samp %>%
  filter(!(time_step %in% recent_time_steps),
         time_step %in% time_steps_centuries) %>%
  pivot_wider(names_from = time_step, values_from = anthrome) %>%
  select(-id) %>%
  nomclust(prox = FALSE, measure = 've')

clusters_decades <- cluster_samp %>%
  filter(!(time_step %in% recent_time_steps),
         time_step %in% time_steps_decades) %>%
  pivot_wider(names_from = time_step, values_from = anthrome) %>%
  select(-id) %>%
  nomclust(prox = FALSE, measure = 've')

hist(clusters$mem$clu_6)
dgg_land$land_area

cluster_samp %>%
  mutate(cluster = clusters$mem$clu_6) %>%
  pivot_longer(-c(id, cluster), names_to = 'time_step', values_to = 'anthrome') %>%
                   dplyr::mutate(time_step = factor(time_step, levels = time_steps_ordered)) %>%
  ggplot(aes(time_step, anthrome, group = id, color = as.factor(cluster))) +
  geom_line(alpha = .5, size = 1.2) +
  facet_wrap(~cluster) +
  theme_classic()
```

```{r}
cluster_samp %>%
  mutate(cluster = clusters$mem$clu_6) %>%
  pivot_longer(-c(id, cluster), names_to = 'time_step', values_to = 'anthrome') %>%
                   dplyr::mutate(time_step = factor(time_step, levels = time_steps_ordered)) %>%
  group_by(cluster, time_step) %>%
  dplyr::summarise(anthrome = modal(anthrome)) %>%
  left_join(anthrome_key, by = c('anthrome' = 'value'))
```

```{r}

hyde_dgg_long <- map(hyde_dgg, pivot_hyde)


write_csv(hyde_dgg_time, 'hyde_dgg_time.csv')
```


```{r}
anthromes_dgg %>%
  mutate(id = as.integer(id), anthrome = as.integer(anthrome)) %>%
  pivot_wider(names_from = time_step, values_from = anthrome)
```

```{r}
hyde_dgg_time %>%
  pull(time_step) %>% unique
```

#####
Create final masks and grids

Creating land masks
```{r, eval = FALSE}
dgg_land <- read_sf('l12_ISEA3H_dgg_land.shp')

#this is erles mask
land_mask <- read_sf('../an12_dgg_cells.shp') %>%
  filter(DGG_status == 3) %>%
  pull(ANL12_ID)

fixed_inputs <- read_csv('fixed_inputs.csv') %>%
  mutate(id = dgg_land$id)

an12_fixed_inputs <- dgg_land %>% 
  filter(id %in% land_mask) %>% 
  left_join(fixed_inputs) %>%
  select(id, land_area, pot_veg, pot_vill, geometry) %>%
    st_set_crs(4326)

an12_dgg <- read_csv('anthromes_dgg.csv') %>%
  filter(id %in% an12_dgg_inputs$id)%>%
  pivot_longer(-id, names_to = 'time_step', values_to = 'anthrome') %>%
  left_join(time_key) %>%
  filter(year <= 2000) %>%
  arrange(id, year, anthrome) %>%
  mutate(id = as.integer(id), anthrome = as.integer(anthrome)) %>%
  select(-year) %>%
  pivot_wider(names_from = time_step, values_from = anthrome)

write_sf(an12_fixed_inputs, 'an12_dgg_inputs.shp')
write_csv(an12_dgg, 'an12_dgg.csv')
```



# DGG from analysis script
```{r}
# construct the DGG
dggs <- dgconstruct(res=12)

#save the DGG
dgearthgrid(dggs, frame = TRUE, wrapcells = FALSE, savegrid =  "./l12_ISEA3H_dgg.shp")

dgg <- dgconstruct(res = 12) %>%
  dgearthgrid(frame = TRUE, wrapcells = FALSE, savegrid = 'dgg_l12.shp')


grid <- dgconstruct(res = 7) %>%
  dgearthgrid(frame = FALSE, wrapcells = FALSE) %>%
  st_as_sf() %>%
  mutate(id = 1:n()) %>%
  st_wrap_dateline(options = c("WRAPDATELINE=YES", "DATELINEOFFSET=30")) %>%
  .[land_mask, ]

 #%>% st_set_crs('+proj=isea')
plot(grid)
```

```{r}
dgg12 <- read_sf('data/raw_data/l12_ISEAH_dgg.shp/l12_ISEA3H_dgg.shp')

dgg12 <- st_set_crs(dgg12 , st_crs(anthromes))
```
